### ISSUE TITLE
The field 'State' contains the value 'New' that is not in the list of supported values

### ISSUE THREAD

**Issue by craigloewen-msft** [microsoft/gh-sync#13]
Hi I have gh-sync set up here: 
https://github.com/microsoft/WSL/blob/master/.github/workflows/gh-sync.yml

I am seeing this issue when trying to run it:
`Unhandled exception: Microsoft.TeamFoundation.WorkItemTracking.WebApi.RuleValidationException: The field 'State' contains the value 'New' that is not in the list of supported values`, which isn't allowing us to sync issues.

Any idea on how to fix or resolve it?

Full code dump:
```
Getting GitHub issue microsoft/WSL#9169...
Got profile OK!
Got GitHub client.
Got repository: https://github.com/microsoft/WSL.
Got issue: https://github.com/microsoft/WSL/issues/9169.
Got profile OK!
Added 1 comments from GitHub issue.
Unhandled exception: Microsoft.TeamFoundation.WorkItemTracking.WebApi.RuleValidationException: The field 'State' contains the value 'New' that is not in the list of supported values
   at Microsoft.VisualStudio.Services.WebApi.VssHttpClientBase.HandleResponseAsync(HttpResponseMessage response, CancellationToken cancellationToken)
   at Microsoft.VisualStudio.Services.WebApi.VssHttpClientBase.SendAsync(HttpRequestMessage message, HttpCompletionOption completionOption, Object userState, CancellationToken cancellationToken)
   at Microsoft.VisualStudio.Services.WebApi.VssHttpClientBase.SendAsync[T](HttpRequestMessage message, Object userState, CancellationToken cancellationToken)
   at Microsoft.VisualStudio.Services.WebApi.VssHttpClientBase.SendAsync[T](HttpMethod method, IEnumerable`1 additionalHeaders, Guid locationId, Object routeValues, ApiResourceVersion version, HttpContent content, IEnumerable`1 queryParameters, Object userState, CancellationToken cancellationToken)
   at Microsoft.GhSync.Synchronizer.<>c__DisplayClass[12](https://github.com/microsoft/WSL/actions/runs/3527624557/jobs/5916928330#step:3:13)_0.<<UpdateState>b__0>d.MoveNext() in /app/src/GhSync/Services/Synchronizer.cs:line 57
--- End of stack trace from previous location ---
   at Microsoft.GhSync.Extensions.Bind[TResult,TNewResult](Task`1 task, Func`2 continuation) in /app/src/GhSync/Extensions/Extensions.cs:line 2[13](https://github.com/microsoft/WSL/actions/runs/3527624557/jobs/5916928330#step:3:14)
   at Microsoft.GhSync.Synchronizer.UpdateState(WorkItem workItem, Issue issue) in /app/src/GhSync/Services/Synchronizer.cs:line 55
   at Microsoft.GhSync.Synchronizer.PullGitHubIssue(Issue ghIssue, Boolean dryRun, Boolean allowExisting) in /app/src/GhSync/Services/Synchronizer.cs:line 42
   at Microsoft.GhSync.Program.<PullIssueCommand>b__3_0(String repo, Int32 issueId, Boolean dryRun, Boolean allowExisting) in /app/src/GhSync/Program.cs:line 61
   at System.CommandLine.Invocation.AnonymousCommandHandler.InvokeAsync(InvocationContext context)
   at System.CommandLine.Invocation.InvocationPipeline.<>c__DisplayClass4_0.<<BuildInvocationChain>b__0>d.MoveNext()
--- End of stack trace from previous location ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c__DisplayClass18_0.<<UseParseErrorReporting>b__0>d.MoveNext()
--- End of stack trace from previous location ---
   at Microsoft.GhSync.Program.<>c__DisplayClass8_0.<<Invoke>b__0>d.MoveNext() in /app/src/GhSync/Program.cs:line [17](https://github.com/microsoft/WSL/actions/runs/3527624557/jobs/5916928330#step:3:18)9
--- End of stack trace from previous location ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c__DisplayClass13_0.<<UseHelp>b__0>d.MoveNext()
--- End of stack trace from previous location ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c__DisplayClass22_0.<<UseVersionOption>b__0>d.MoveNext()
--- End of stack trace from previous location ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c__DisplayClass20_0.<<UseTypoCorrections>b__0>d.MoveNext()
--- End of stack trace from previous location ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c.<<UseSuggestDirective>b__[19](https://github.com/microsoft/WSL/actions/runs/3527624557/jobs/5916928330#step:3:20)_0>d.MoveNext()
--- End of stack trace from previous location ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c__DisplayClass17_0.<<UseParseDirective>b__0>d.MoveNext()
--- End of stack trace from previous location ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c.<<RegisterWithDotnetSuggest>b__6_0>d.MoveNext()
--- End of stack trace from previous location ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c__DisplayClass9_0.<<UseExceptionHandler>b__0>d.MoveNext()
```

Thanks!

**Comment by ntrappe-msft** [comment]
Same issue here. I wish there was a way we could map the GitHub 'New' to a state on ADO.
